title: Christian Johnson's Blog
email: christian@johnsonfamilyhub.com
description: >-
  Documenting my journey into homelabs, automation, and self-hosting.
theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes"
